# -*- coding: utf-8 -*-
"""Data driven. Unit Economics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPaOayu3Ge_n7ddu6fQ6ywFbnPYz3ZHP
"""

import pandas as pd
import numpy as np

"""# **Extract data**"""

# function for read tất cả gg sheet
def read_ggsheet (google_sheet_id):
  url='https://docs.google.com/spreadsheets/d/' + google_sheet_id + '/export?format=xlsx'
  df = pd.read_excel(url)
  return df
google_sheet_id = ['1by8tPHwOnq3uKYK2E7sA9VBUYoPM4p1Rnrm_Ss9cyHI',
                   '1AZOIThOV4P-0eYDge53ZwumVkfkHoYPWxst3k3Bv87c',
                   '10OGbaywwMIqKgnPGy8VDvpBVtjyqln47iYa2lFhI9Mw',
                   '1c_WihqTZCQvNgxzmd-OwhR9i5diwtfxXVLyMn8R-Lp4',
                   '1qayqML1zCKdmtzutkcy9LWvE6xFRm6TGBEVkHHJKIuE']
for id in google_sheet_id:
  read_ggsheet(id)

customer_lifespan_data = pd.read_excel('https://docs.google.com/spreadsheets/d/1by8tPHwOnq3uKYK2E7sA9VBUYoPM4p1Rnrm_Ss9cyHI/export?format=xlsx', sheet_name='Sheet1')

daily_marketing_spendings = pd.read_excel('https://docs.google.com/spreadsheets/d/1AZOIThOV4P-0eYDge53ZwumVkfkHoYPWxst3k3Bv87c/export?format=xlsx', sheet_name='Sheet1')

monthly_expenses = pd.read_excel('https://docs.google.com/spreadsheets/d/10OGbaywwMIqKgnPGy8VDvpBVtjyqln47iYa2lFhI9Mw/export?format=xlsx', sheet_name='Sheet1')

payroll = pd.read_excel('https://docs.google.com/spreadsheets/d/1c_WihqTZCQvNgxzmd-OwhR9i5diwtfxXVLyMn8R-Lp4/export?format=xlsx', sheet_name='Sheet1')

receipts_history = pd.read_excel('https://docs.google.com/spreadsheets/d/1qayqML1zCKdmtzutkcy9LWvE6xFRm6TGBEVkHHJKIuE/export?format=xlsx', sheet_name='Sheet1')

def get_last_month(dataset,date_col):
  last_month = dataset[date_col].max().month
  cond = dataset[date_col].dt.month == last_month
  return dataset[cond]

customer_lifespan_data.head()

daily_marketing_spendings.head()

monthly_expenses.head()

monthly_expenses.item.unique()

payroll.head()

payroll.department.unique()

receipts_history.head()

daily_marketing_spendings = daily_marketing_spendings.convert_dtypes()

payroll = payroll.convert_dtypes()

monthly_expenses = monthly_expenses.convert_dtypes()

"""# **Calculation**

# **CAC - Customer Aquisition Cost**
"""

# tính CRM

last_month = monthly_expenses.month.max()

last_month_expenses = monthly_expenses[monthly_expenses['month'] == last_month]

# cách 1
cond = last_month_expenses['item'] == 'Salesforce'
crm_cost = last_month_expenses[cond]['amount'].values[0]
print(crm_cost)

# cách 2
CRM = monthly_expenses[(monthly_expenses['month'].dt.month == 3) & (monthly_expenses['item'] == 'Salesforce')]['amount'].sum()

print(CRM)

# Marketing spending in mar 2023
Total_marketing_spending_mar = daily_marketing_spendings[daily_marketing_spendings['date'].dt.month == 3].spending.sum()
print(Total_marketing_spending_mar)

# spending on each marketing chanel on mar
daily_marketing_spendings[(daily_marketing_spendings['date'].dt.month == 3)].groupby('channel')['spending'].sum()

# total sales (  sales and marketing department in mar)

df_sales_marketing = payroll[payroll['department'].isin(['Sales', 'Marketing'])]
df_sales_marketing.head()

total_sales_mar = df_sales_marketing[df_sales_marketing['month'].dt.month == 3].paid.sum()
print(total_sales_mar)

df_sales_marketing[df_sales_marketing['month'].dt.month == 3].count()
# there are 6 staffs in sales and marketing department

# total new customer in mar 2023
total_newcus_mar = receipts_history[receipts_history['date'].dt.month == 3].new_customer.sum()
print(total_newcus_mar)

# CAC
CAC = (CRM + Total_marketing_spending_mar + total_sales_mar )/total_newcus_mar
print(CAC)

"""# **ARPU - Average revenue per user**"""

# Total number of user in Mar
total_user_mar = receipts_history[receipts_history['date'].dt.month == 3].customer_id.count()
print(total_user_mar)

# total revenue in mar
total_revenue_mar = receipts_history[receipts_history['date'].dt.month == 3].receipt_amount.sum()
print(total_revenue_mar)

# ARPU
ARPU = total_revenue_mar / total_user_mar
print(ARPU)

 # meaning each customers generated $266.98 in revenue on average in mar

"""# **COGS - Cost of Goods Sold**"""

# PRODUCTION COST  = AWS Hosting,  Google Cloud Storage, Atlassian Jira

production_expense_tab = monthly_expenses[monthly_expenses['item'].isin(['AWS Hosting', 'Google Cloud Storage', 'Atlassian Jira'])]

production_cost = production_expense_tab[
    production_expense_tab['month'].dt.month == 3
]['amount'].sum()

production_cost

# epense for each item (production cost) in mar
production_expense_tab[production_expense_tab['month'].dt.month == 3].groupby('item')['amount'].sum()

from typing import SupportsFloat
# solfware cost : item slack and zoom
solfware_table = monthly_expenses[monthly_expenses['item'].isin(['Slack', 'Zoom'])]
solfware_cost = solfware_table[solfware_table['month'].dt.month == 3]['amount'].sum() * 0.6
solfware_cost

# production_salary_cost = department - eninerring

production_salary_cost = payroll[(payroll['month'].dt.month == 3) & (payroll['department'] == 'Engineering')]['paid'].sum()
production_salary_cost

payroll[(payroll['month'].dt.month == 3) & (payroll['department'] == 'Engineering')].count()
# there are 3 staff in Engineering deparment

# COGS

COGS = production_cost + solfware_cost + production_salary_cost
print(COGS)

"""# **Gross Margin**"""

# revenue
revenue = receipts_history[receipts_history['date'].dt.month == 3].receipt_amount.sum()
print(revenue)

gross_margin = (revenue - COGS)/revenue * 100
print(gross_margin)

"""# **LTV - lifetime value**"""

customer_lifespan = (customer_lifespan_data.churn_date - customer_lifespan_data.start_date).dt.days

average_customer_lifespan = customer_lifespan.mean()
average_customer_lifespan_permonth = average_customer_lifespan/30
print(average_customer_lifespan_permonth)

LTV = ARPU * average_customer_lifespan_permonth * gross_margin/100
print(LTV)

"""# **LTV / CAC**"""

LTV/CAC

"""# **Conclusion**

- CAC = 1213.97 pretty high
- ARPU = 266.99 the Average Revenue Per User
(ARPU)  is 266.99, meaning each customers generated $266.99 in revenue on average
during the month.
- COGS = 20264 costs of producing the goods is 20264 dola
- Gross margin = 75.59%   gross margin is 75.59% which higher than 50% is
considered as a pretty good indicator. It is scalable
- LTV = 1986.27 Lifetime value of a customer is 1986.27 dola
- LTV/CAC = 1.636 A ratio greater than 1 indicates that the company is generating more revenue from
customers than it costs to acquire them. This is a positive sign, suggesting profitability
and sustainable growth. However, this is not ideal ratio

# **Recommendations**

- CAC is pretty high, especially spending on marketings which is quite high. We should evaluate the effectiveness of each marketing channel and consider reduce cost for the less effective channel. Moreover, also salary of markerting manager is highest, however the efficiency of marketing need to be re-evaluate since we spent alot on it. After evaluating, we can reconsider about salary which we paid with their contributions.
- Gross margin is 75.59% this number show that we can scale Streamline Pro
- opimize COGS : production cost is majority, and AWS Hosting is double the rest. We can consider reduce this cost by finding alternative provider, ask advice from engineering to optimize cost for AWS Hosting.
- Increse LTV : Reduce COGS as suggestion above, and consider clasify customer type to support customer better, from that can increase churn
"""